name: SSH NODE CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
      if: ${{ env.DEPLOY_SSH != '' }}

    - name: Clean folder
      run: rm -rf README.md .git
      if: ${{ env.DEPLOY_SSH != '' }}

    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@v2.1.5
      if: ${{ env.DEPLOY_SSH != '' }}
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "src/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}

    env:
      DEPLOY_SSH: ${{ secrets.REMOTE_TARGET }}
